import { createServiceClient } from "@/lib/supabase/server";

export async function GET(_request: Request, { params }: { params: Promise<{ candidateId: string }> }) {
  const { candidateId } = await params;
  const supabase = createServiceClient();

  const { data: candidate } = await supabase
    .from("candidates_pipeline")
    .select("*, job_postings!inner(title, pay_range, shift_type, locations!inner(name, address))")
    .eq("id", candidateId)
    .single();

  if (!candidate) return new Response("Candidate not found", { status: 404 });

  const job = candidate.job_postings as Record<string, unknown>;
  const location = job.locations as Record<string, string>;
  const today = new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" });

  const html = `<!DOCTYPE html>
<html>
<head><meta charset="UTF-8"><title>Offer Letter — ${candidate.name}</title>
<style>
  body { font-family: Georgia, serif; max-width: 700px; margin: 40px auto; padding: 40px; color: #1a1a2e; line-height: 1.8; }
  .header { text-align: center; margin-bottom: 40px; }
  .header h1 { font-size: 28px; margin-bottom: 4px; }
  .header p { color: #666; font-size: 14px; }
  .field { font-weight: bold; color: #003DA5; }
  .signature { margin-top: 60px; }
  .signature-line { border-top: 1px solid #333; width: 250px; margin-top: 40px; padding-top: 8px; }
  .no-print { text-align: center; margin-bottom: 20px; }
  @media print { .no-print { display: none; } body { margin: 0; padding: 20px; } }
</style>
</head>
<body>
  <div class="no-print">
    <button onclick="window.print()" style="background:#003DA5;color:white;border:none;padding:10px 20px;border-radius:8px;cursor:pointer;">📄 Print / Save as PDF</button>
  </div>

  <div class="header">
    <h1>OFFER OF EMPLOYMENT</h1>
    <p>${location.name}<br>${location.address}</p>
  </div>

  <p>${today}</p>

  <p>Dear <span class="field">${candidate.name}</span>,</p>

  <p>We are pleased to offer you the position of <span class="field">${job.title}</span> at <span class="field">${location.name}</span>. We believe your skills and experience will be a valuable asset to our team.</p>

  <p><strong>Position Details:</strong></p>
  <ul>
    <li><strong>Title:</strong> ${job.title}</li>
    <li><strong>Location:</strong> ${location.name}, ${location.address}</li>
    <li><strong>Compensation:</strong> ${job.pay_range}</li>
    <li><strong>Schedule:</strong> ${job.shift_type}</li>
    <li><strong>Start Date:</strong> To be determined upon acceptance</li>
  </ul>

  <p>This offer is contingent upon successful completion of a background check and verification of your eligibility to work in the United States.</p>

  <p>Please indicate your acceptance of this offer by signing below and returning this letter within 5 business days.</p>

  <p>We look forward to welcoming you to the team!</p>

  <div class="signature">
    <p>Sincerely,</p>
    <div class="signature-line">
      <p>Store Manager<br>${location.name}</p>
    </div>
  </div>

  <div class="signature" style="margin-top: 40px;">
    <p><strong>Acceptance:</strong></p>
    <p>I, ${candidate.name}, accept this offer of employment.</p>
    <div class="signature-line">
      <p>Signature &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Date</p>
    </div>
  </div>

  <p style="margin-top: 40px; font-size: 12px; color: #999; text-align: center;">Generated by Vertex Autopilot · Vertex Lab Solutions © 2026</p>
</body>
</html>`;

  return new Response(html, { headers: { "Content-Type": "text/html" } });
}
